# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

resources:
  - db-config.yaml
  - db-depl.yaml
  - db-service.yaml

commonLabels:
  feature: database

nameSuffix: -storage

images: 
  - name : mongo
    newName : postgres
    newTag: '4.2'
