apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx/
  - message-broker/
  - db/

commonLabels:
  department: engineering
namespace: debugging

namePrefix: BharatCloud-